#!/usr/bin/env node
/**
 * =============================================================================
 * RODSCHINSON — AI-Generated Image Post Renderer
 * =============================================================================
 * Takes an HTML file (generated by Claude) and renders it to a PNG at the
 * specified format dimensions.
 *
 * USAGE:
 *   node ai_image_renderer.js --html PATH.html --output PATH.png \
 *                             --format 1x1|4x5|9x16|16x9
 * =============================================================================
 */
'use strict';
const puppeteer = require('puppeteer');
const fs   = require('fs');
const path = require('path');

const FORMATS = {
  '1x1':  { width: 1080, height: 1080 },
  '4x5':  { width: 1080, height: 1350 },
  '9x16': { width: 1080, height: 1920 },
  '16x9': { width: 1920, height: 1080 },
  '1:1':  { width: 1080, height: 1080 },
  '4:5':  { width: 1080, height: 1350 },
  '9:16': { width: 1080, height: 1920 },
  '16:9': { width: 1920, height: 1080 },
};

function parseArgs() {
  const args = process.argv.slice(2);
  const get  = (f) => { const i = args.indexOf(f); return i !== -1 && args[i+1] ? args[i+1] : null; };
  return {
    html:    get('--html'),
    output:  get('--output'),
    format:  get('--format') || '1x1',
  };
}

async function main() {
  const opts = parseArgs();
  if (!opts.html || !fs.existsSync(opts.html)) {
    console.error('Usage: node ai_image_renderer.js --html PATH --output PATH [--format 1x1]');
    process.exit(1);
  }

  const dim = FORMATS[opts.format] || FORMATS['1x1'];
  console.log(`[ai-image] Rendering ${opts.html} at ${dim.width}x${dim.height}`);

  const browser = await puppeteer.launch({
    headless: 'new',
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-gpu',
           '--disable-dev-shm-usage', '--font-render-hinting=none',
           '--allow-file-access-from-files'],
  });

  try {
    const page = await browser.newPage();
    await page.setViewport({ width: dim.width, height: dim.height, deviceScaleFactor: 2 });
    await page.goto(`file://${path.resolve(opts.html)}`, { waitUntil: 'networkidle0', timeout: 30000 });
    await page.evaluate(() => document.fonts.ready).catch(() => {});
    await new Promise(r => setTimeout(r, 500));

    const outPath = opts.output || opts.html.replace(/\.html?$/, '.png');
    await page.screenshot({
      path: outPath,
      type: 'png',
      clip: { x: 0, y: 0, width: dim.width, height: dim.height },
    });
    console.log(`[ai-image] PNG -> ${outPath}`);
    await page.close();
  } finally {
    await browser.close();
  }
}

main().catch(e => { console.error('Fatal:', e.message); process.exit(1); });
